const MENU_ITEMS = [
    {
        id: 'm1',
        type: 'Appetizer',
        name: 'Sashimi 刺身',
        description: `Tuna, Yellowtail, Salmon. Everyone's favorite`,
        price: 17.25,
    },
    {
        id: 'm2',
        type: 'Appetizer',
        name: 'Carpaccio カルパッチョまぐろ/鮭',
        description: 'Tuna or Salmon',
        price: 18.50,
    },
    {
        id: 'm3',
        type: 'Appetizer',
        name: 'Carpaccio カルパッチョはまち/平目',
        description: 'Yellowtail or Halibut',
        price: 19.50,
    },
    {
        id: 'm4',
        type: 'Appetizer',
        name: 'Mix Carpaccio カルパッチョ まぐろ/鮭/はまち/平目',
        description: 'Tuna, Salmon, Yellowtail and Halibut (2 pieces each)',
        price: 20.50,
    },
    {
        id: 'm5',
        type: 'Appetizer',
        name: 'Bay Special ベイスペシャル',
        description: 'Scallop, Shrimp, 2 kinds of fish w/ Special Sauce',
        price: 14.50,
    },
    {
        id: 'm6',
        type: 'Appetizer',
        name: 'Spicy Bay Special スパイシーベイ ス ペシャル',
        description: 'Scallop, Shrimp, 2 kinds of fish w/ Spicy Sauce',
        price: 15.50,
    },
    {
        id: 'm7',
        type: 'Appetizer',
        name: 'Kama Hamachi かま 鮭',
        description: 'Broiled Yellowtail Cheek (1 piece)',
        price: 17.50,
    },
    {
        id: 'm8',
        type: 'Appetizer',
        name: 'Kama Sake かま 鮭',
        description: 'Broiled Salmon Cheek (1 piece)',
        price: 12,
    },
    {
        id: 'm9',
        type: 'Appetizer',
        name: 'Soft Shell Crab ソフトシェルクラブ',
        description: 'Deep fried soft shell crab (1 piece)',
        price: 10.75,
    },
    {
        id: 'm10',
        type: 'Appetizer',
        name: 'Soft Shell Crab ソフトシェルクラブ',
        description: 'Deep fried soft shell crab (2 pieces)',
        price: 16,
    },
    {
        id: 'm11',
        type: 'Appetizer',
        name: 'Steamed Clam あさりの酒蒸し',
        description: 'Sake-steamed clam in broth',
        price: 16,
    },
    {
        id: 'm12',
        type: 'Appetizer',
        name: 'Yakiniku 焼肉',
        description: 'Japanese-Korean Style B.B.Q. Beef',
        price: 12.50,
    },
    {
        id: 'm13',
        type: 'Appetizer',
        name: 'Broiled Fish 焼き魚 (鮭)',
        description: 'Broiled Salmon',
        price: 12.00,
    },
    {
        id: 'm14',
        type: 'Appetizer',
        name: 'Broiled Fish 焼き魚 (鯖)',
        description: 'Broiled Japanese Mackerel',
        price: 12.00,
    },
    {
        id: 'm15',
        type: 'Appetizer',
        name: 'Mentai-Ko 明太子',
        description: 'Spicy Cod Roe',
        price: 11.50,
    },
    {
        id: 'm16',
        type: 'Appetizer',
        name: 'Shrimp & Vegetable Tempura 海老、野菜天ぷら',
        description: 'Shrimp Tempura (4 pieces) and Vegetable Tempura (6 pieces)',
        price: 13.5,
    },
]

export default MENU_ITEMS;